name: Test

on:
  pull_request:

jobs:
  j2lint-test:
    name: Check J2
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Run j2lint
        uses: ansible-actions/j2lint-action@v0.0.1
        with:
          target: "./templates"

  required_status_checks:
    name: Required Terraform Test Status Checks
    runs-on: ubuntu-latest
    needs:
      - j2lint-test
    if: always() && !cancelled()
    timeout-minutes: 5
    steps:
      - run: |
          [ '${{ needs.j2lint-test.result }}' = 'success' ] || (echo j2lint-test failed && false)
