name: Test

on:
  pull_request:

jobs:
  fmt-validate-test:
    name: Check Terraform
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ secrets.TERRAFORM_VERSION }}

      - name: Terraform fmt
        id: fmt
        run: terraform fmt -check -recursive ./modules ./templates

      - name: Terraform init
        id: init
        run: terraform init -backend=false

      - name: Terraform validate
        id: validate
        if: success() || failure()
        run: terraform validate
  required_status_checks:
    name: Required Terraform Test Status Checks
    runs-on: ubuntu-latest
    needs:
      - fmt-validate-test
    if: always() && !cancelled()
    timeout-minutes: 5
    steps:
      - run: |
          [ '${{ needs.fmt-validate-test.result }}' = 'success' ] || (echo fmt-validate-test failed && false)
